name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        # Optional: install torch if available (skip on failure)
        pip install torch || echo "PyTorch not installed, skipping"
    
    - name: Run tests
      run: |
        # Run all test_*.py scripts
        for test_file in test_*.py; do
          if [ -f "$test_file" ]; then
            echo "Running $test_file..."
            python "$test_file" || exit 1
          fi
        done
        echo "All tests passed!"
